create database MML;

use MML;

CREATE TABLE usuario (
  IDUsuario INT AUTO_INCREMENT NOT NULL,
  Usuario VARCHAR(255) NOT NULL,
  Nome VARCHAR(255) NOT NULL,
  DtNasc DATE NOT NULL,
  Senha VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  ISAdmin BOOLEAN NOT NULL DEFAULT FALSE,
  Imagem VARCHAR(255) NOT NULL DEFAULT 'noImage',
  PRIMARY KEY (IDUsuario)
);

CREATE TABLE amizade (
  IDAmizade INT AUTO_INCREMENT NOT NULL,
  State INT NOT NULL,
  InicioAmizade DATE NOT NULL,
  Seguidor INT NOT NULL,
  Seguido INT NOT NULL,
  PRIMARY KEY (IDAmizade),
  FOREIGN KEY (Seguidor) REFERENCES usuario(IDUsuario) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Seguido) REFERENCES usuario(IDUsuario) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE reclamacao (
  IDReclamacao INT AUTO_INCREMENT NOT NULL,
  Descricao VARCHAR(255) NOT NULL,
  Resposta VARCHAR(255),
  IDUsuario INT NOT NULL,
  IDUsuarioAdmin INT,
  PRIMARY KEY (IDReclamacao),
  FOREIGN KEY (IDUsuario) REFERENCES usuario(IDUsuario) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (IDUsuarioAdmin) REFERENCES usuario(IDUsuario) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE filme (
    IDFilme INT AUTO_INCREMENT NOT NULL,
    Titulo VARCHAR(255) NOT NULL,
    Sinopse VARCHAR(1000) NOT NULL,
    Lancamento DATE NOT NULL,
    NotaGeral FLOAT NOT NULL,
    IdadeIndicativa INT NOT NULL,
    Imagem VARCHAR(255) NOT NULL DEFAULT 'noImage',
    PRIMARY KEY (IDFilme)
);

CREATE TABLE listaFilme (
    IDListaFilme INT AUTO_INCREMENT NOT NULL,
    Favorito BOOLEAN NOT NULL DEFAULT false,
    IDFilme INT NOT NULL,
    IDUsuario INT NOT NULL,
    PRIMARY KEY (IDListaFilme),
    FOREIGN KEY (IDFilme) REFERENCES filme(IDFilme) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (IDUsuario) REFERENCES usuario(IDUsuario) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE pretendeAssistirFilme (
  IDPAF INT AUTO_INCREMENT NOT NULL,
  IDFilme INT NOT NULL,
  IDUsuario INT NOT NULL,
  PRIMARY KEY (IDPAF),
  FOREIGN KEY (IDFilme) REFERENCES filme(IDFilme) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (IDUsuario) REFERENCES usuario(IDUsuario) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE serie (
  IDSerie INT AUTO_INCREMENT NOT NULL,
  Titulo VARCHAR(255) NOT NULL,
  Sinopse VARCHAR(255) NOT NULL,
  Lancamento DATE NOT NULL,
  NotaGeral FLOAT NOT NULL DEFAULT 0,
  IdadeIndicativa INT NOT NULL,
  Imagem VARCHAR(255) NOT NULL DEFAULT 'noImage',
  PRIMARY KEY (IDSerie)
);

CREATE TABLE listaSerie (
    IDListaSerie INT AUTO_INCREMENT NOT NULL,
    Favorito BOOLEAN NOT NULL DEFAULT false,
    IDUsuario INT NOT NULL,
    IDSerie INT NOT NULL,
    PRIMARY KEY (IDListaSerie),
    FOREIGN KEY (IDUsuario) REFERENCES usuario(IDUsuario) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (IDSerie) REFERENCES serie(IDSerie) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE pretendeAssistirSerie (
  IDPAS INT AUTO_INCREMENT NOT NULL,
  IDUsuario INT NOT NULL,
  IDSerie INT NOT NULL,
  PRIMARY KEY (IDPAS),
  FOREIGN KEY (IDUsuario) REFERENCES usuario(IDUsuario) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (IDSerie) REFERENCES serie(IDSerie) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE temporada (
  IDTemporada INT AUTO_INCREMENT NOT NULL,
  Titulo VARCHAR(255) NOT NULL,
  Sinopes VARCHAR(255) NOT NULL,
  Lancamento DATE NOT NULL,
  NotaGeral FLOAT NOT NULL DEFAULT 0,
  Imagem VARCHAR(255) NOT NULL DEFAULT 'noImage',
  IDSerie INT NOT NULL,
  PRIMARY KEY (IDTemporada),
  FOREIGN KEY (IDSerie) REFERENCES serie(IDSerie) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ep (
  IDEp INT AUTO_INCREMENT NOT NULL,
  Titulo VARCHAR(255) NOT NULL,
  Sinopse VARCHAR(255) NOT NULL,
  Lancamento DATE NOT NULL,
  NotaGeral FLOAT NOT NULL DEFAULT 0,
  Imagem VARCHAR(255) NOT NULL DEFAULT 'noImage',
  IDTemporada INT NOT NULL,
  PRIMARY KEY (IDEp),
  FOREIGN KEY (IDTemporada) REFERENCES temporada(IDTemporada) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE pessoa (
  IDPessoa INT AUTO_INCREMENT NOT NULL,
  Nome VARCHAR(255) NOT NULL,
  DtNasc DATE NOT NULL,
  Cargo VARCHAR(255) NOT NULL,
  Imagem VARCHAR(255) NOT NULL DEFAULT 'noImage',
  PRIMARY KEY (IDPessoa)
);

CREATE TABLE elencoFilme (
  IDelencoFilme INT AUTO_INCREMENT NOT NULL,
  IDPessoa INT NOT NULL,
  IDFilme INT NOT NULL,
  PRIMARY KEY (IDelencoFilme),
  FOREIGN KEY (IDPessoa) REFERENCES pessoa(IDPessoa) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (IDFilme) REFERENCES filme(IDFilme) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE elencoSerie (
    IDelencoSerie INT AUTO_INCREMENT NOT NULL,
    IDPessoa INT NOT NULL,
    IDSerie INT NOT NULL,
    PRIMARY KEY (IDelencoSerie),
    FOREIGN KEY (IDPessoa) REFERENCES pessoa(IDPessoa) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (IDSerie) REFERENCES serie(IDSerie) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE genero (
    IDGenero INT AUTO_INCREMENT NOT NULL,
    Nome VARCHAR(255) NOT NULL,
    PRIMARY KEY (IDGenero)
);

CREATE TABLE generoFilme (
    IDGeneroFilme INT AUTO_INCREMENT NOT NULL,
    IDFilme INT NOT NULL,
    IDGenero INT NOT NULL,
    PRIMARY KEY (IDGeneroFilme),
    FOREIGN KEY (IDFilme) REFERENCES filme(IDFilme) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (IDGenero) REFERENCES genero(IDGenero) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE generoSerie (
    IDGeneroSerie INT AUTO_INCREMENT NOT NULL,
    IDSerie INT NOT NULL,
    IDGenero INT NOT NULL,
    PRIMARY KEY (IDGeneroSerie),
    FOREIGN KEY (IDSerie) REFERENCES serie(IDSerie) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (IDGenero) REFERENCES genero(IDGenero) ON DELETE CASCADE ON UPDATE CASCADE
);
